### ISSUE TITLE
incorrect value written to memory after returning from a STATICCALL

### ISSUE THREAD

**Issue by MiladKetabGhale** [ConsenSys/evm-dafny#388] opened 2022-10-20 03:18 UTC
The following is failing:

[503] (tests/GeneralStateTests/stStaticCall/static_CallEcrecover0.json,static_CallEcrecover0_Berlin_0_0_0)

The trace below shows us that upon returning from the STATICCALL, what has been written to memory is incorrect.

**Comment by DavePearce** [comment] 2022-11-15 04:20
Having looked at this now, I think this is just really a duplicate of #338.  Basically, the `ECDSARECOVER` precompiled contract is not implemented yet.

**Closed by DavePearce** 2022-11-15 04:20 UTC
